version: '3.7'
services:

    gonvd:
        container_name: gonvd
        build: .
        volumes:
            - ./:/usr/local/mounted
        ports:
          - "8000:8000"
        environment:
            DEV_TEST_DEBUG: "true"
            MUX_ADDR: ":8000"
            CVE_FEEDS_DIR: /usr/local/cve
            CVE_WORKER_POOL_SIZE: "4"

    itests:
        container_name: itests
        build: ./itests/.
        environment:
            HOSTNAME: gonvd
            PORT: "8000"
