version: '3.7'
services:

    cli:
        container_name: gonvd
        build: .
        volumes:
            - ./:/usr/local/mounted
        environment:
            #- SLEEP_SECONDS: 0
            SLEEP_SECONDS: "99999"
            MUX_ADDR: ":8000"
            CVE_FEEDS_DIR: /usr/local/cves

    itests:
        container_name: itests
        build: ./itests/.
        environment:
            HOSTNAME: gonvd
            PORT: "8000"
